baseURL = "http://example.org/"
languageCode = "en-us"
title = "Octapress - Premium Managed Wordpress Hosting"
theme = "agico-hugo"
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/font-awesome/font-awesome.min.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  URL = "plugins/aos/aos.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/aos/aos.js"



# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Service"
  URL = "service"
  weight = 3

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 4

  [[menu.main]]
  name = "Team"
  URL = "team"
  weight = 6

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 7

  [[menu.main]]
  weight = 8
  name = "Pages"
  hasChildren = true

    [[menu.main]]
    parent = "Pages"
    name = "Pricing"
    URL = "pricing"

    [[menu.main]]
    parent = "Pages"
    name = "Career"
    URL = "career"

#Footer menu

  [[menu.footer]]
  name = "Company History"
  URL = "about"

  [[menu.footer]]
  name = "About us"
  URL = "about"

  [[menu.footer]]
  name = "Contact us"
  URL = "contact"

  [[menu.footer]]
  name = "Services"
  URL = "service"

  [[menu.footer]]
  name = "Privacy Policy"
  URL = "#"

[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Premium Managed Wordpress hosting"
author = "Octapress"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = false

  # Navigation get start button
  [params.navBtn]
  enable = true
  btnText = "sign up"
  URL = "#"

  # Subscription
  [params.subscription]
  title = "Subscribe <br> to our newsletter"
  formAction = "#"

  [params.footer]
  content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud exercitation ullamaboris nisi ut aliquip.exea commodo consequat. Duis aute irure dolor in reprehenderit."

    [[params.footer.socialIcon]]
    icon = "fa-facebook"
    URL = "https://facebook.com/octapress"

    [[params.footer.socialIcon]]
    icon = "fa-twitter"
    URL = "https://twitter.com/octapress"

    [[params.footer.socialIcon]]
    icon = "fa-github"
    URL = "https://github.com/octapress"

    [[params.footer.socialIcon]]
    icon = "fa-instagram"
    URL = "https://instagram.com/octapress"

  [params.footer.service]
  title = "Service"

  [params.footer.contact]
  title = "Contact Info"
  address = "322 Portobello Road, London UK"
  mobile = "+44 7724 615544‬"
  email = "hello@octapress.com"

  # copyright
  [params.copyright]
  copyright = "Octapress"


# share blog post
[[params.sharePost]]
icon = "fa-facebook"
URL = "#"

[[params.sharePost]]
icon = "fa-twitter"
URL = "#"

[[params.sharePost]]
icon = "fa-linkedin"
URL = "#"

[[params.sharePost]]
icon = "fa-google-plus"
URL = "#"
