[build]
  publish = "demo/public"
  command = "make prepare && hugo --source demo --baseURL $URL"

[context.production.environment]
  HUGO_VERSION = "0.54.0"

[context.deploy-preview]
  command = "make prepare && hugo --source demo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.54.0"



# Default site wide settings
[build.processing]
  skip_processing = true

# Branch specific settings
[context.branch-name.processing]
  skip_processing = false
[context.branch-name.processing.css]
  bundle = true
  minify = true
